In [ ]:
#variables
a=10
print("I AM",a,"years old")

I AM 10 years old


In [ ]:
#arthemitic ops int variables
a = int(input("Enter first number:"))
b = int(input("Enter second number:"))
print("sum is",a+b)
print("Difference is",a-b)
print("product is",a*b)
print("Quotient is",a/b)
print("Remainder is",a%b)
print("Power of a to be is",a**b)
print("Float div",a//b)




Enter first number:45
Enter second number:56
sum is 101
Difference is -11
product is 2520
Quotient is 0.8035714285714286
Remainder is 45
Power of a to be is 380102539714517509119234755043630811768952009743379517880956797171165817417204380035400390625
Float div 0


In [ ]:
#take a salary from the  user if the salary is more than 50,000 there is a 10%take tax print his final salary
sal=int(input("Enter your salary:"))
if sal>=50000:
  print(sal-sal*0.1)
else:
  print("Your salary is less than 50k so, no tax")


Enter your salary:30000
Your salary is less than 50k so, no tax


In [ ]:
#Get the salary from the user if the salary is more than or equal to 50000 apply 10% tax dedection,if the salary is less than 50000 apply 5% tax if the salary is more than 70000 apply 12% tax if the salary exceeds 100000 print your are promoted to next level
#0 to 50k --> 5%
#51k to 70k -->10%
#71k to 1l -->12%
#more than 1l --> promotion!
a=int(input("Enter the salary"))
if(a>=0 and a<50000):
  print("Tax is apply 5%",a-(a*5/100));
elif(a>=50000 and a<70000):
  print("Tax is apply 10%",a-(a*10/100));
elif(a>=70000 and a<100000):
  print("Tax is apply 12%",a-(a*12/100));
else:
  print("your salary is more than 100000  your are promoted to next level");


Enter the salary45000
Tax is apply 5% 42750.0



> greater
== equal
!= eq
 logical ops:
 and-both condition true -o/p- true ,
 any condition false -o/p - false
 both condition is false- o/p -false
 or -one condition true -o/p - true
 both condition false -o/p - false


 condiion:
 one con:
 if con:
  st


one con and fail
if con:
 st
 else:
  st
    

mutiple con
if con:
 st
  elif con2:

In [ ]:
#for loop:
num=int(input("enter number:"))
for i in range(1,11):
  print(num, 'x', i, '=', num*i)

enter number:18
18 x 1 = 18
18 x 2 = 36
18 x 3 = 54
18 x 4 = 72
18 x 5 = 90
18 x 6 = 108
18 x 7 = 126
18 x 8 = 144
18 x 9 = 162
18 x 10 = 180


In [ ]:
#while loop
n=int(input('Enter number:'))
i=1
while(i<=10):
  print(n,"*",i,"=",n*i)
  i=i+1


Enter number:5
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50


In [ ]:
#list:heterogenious
l1 =[1,"kill",67,"chat",9.1,True]
for i in l1:
  print(i)

1
kill
67
chat
9.1
True


In [ ]:
#mutable
l1=[1,2,3,"kill"]
l1.append("append")
for i in l1:
  print(i)

1
2
3
kill
append


In [ ]:
#mutable
l1.append("append")
print(l1)
l1.insert(4,"inserted")
print(l1)

[1, 2, 3, 'kill', 'append', 'append']
[1, 2, 3, 'kill', 'inserted', 'append', 'append']


In [ ]:
l2=["moyemoye","poypoye"]
l1.extend(l2)
print(l1)

[1, 2, 3, 'kill', 'inserted', 'append', 'append', 'moyemoye', 'poypoye']


In [ ]:
#pop
l2=["yugn","etybvgtrd","thrbyrf"]
l2.pop(0)
print(l2)

['etybvgtrd', 'thrbyrf']


In [ ]:
#remove
l1=["siris","siri","sirisha"]
l1.remove("siri")
print(l1)

['siris', 'sirisha']


In [ ]:
l=["apple","orange","pineapple"]
l.clear()
print(l)

[]


In [ ]:
#create a list of  10 integers elements print there squares saves this squares in a new list
number=[23,67,12,34,69]
squares=[num*2 for num in number]
print(squares)



[46, 134, 24, 68, 138]


In [ ]:
#LC
#newlist=[output for]
l1=[23,67,12,34,69]
res=[i*i for i in l1]
print(res)

[529, 4489, 144, 1156, 4761]


In [ ]:
#LC
#NEWLIST=[OUTPUT for if]
L1=[23,45,67,74,98]
res=[i*i for i in l1 if i >50]
print(res)

[4489, 4761]


In [ ]:
#LC
#new list =[(st of if)if (cond) else (st of else)for]
l1=[23,45,54,64,65,6]
res=[i*i if i>50 else 'x' for i in l1]
print(res)

['x', 'x', 2916, 4096, 4225, 'x']


In [ ]:
#Take the salary from the user if salary less than 50000 10% tax otherwise 15% tax
sal_list=[78000,80000,100000,90000]
res=[i-i*0.1 if i<50000 else i-i*0.15 for i in sal_list]
print(res)

[66300.0, 68000.0, 85000.0, 76500.0]


In [ ]:
dictionary

dictname={key:val:val.....}


In [ ]:
#create
dict1={"mentor":'jwalitha',56:'sirisha',45:'priya'}
print(dict1)

{'mentor': 'jwalitha', 56: 'sirisha', 45: 'priya'}


In [ ]:
dict1={"mentor":'jwalitha',56:'sirisha',45:'priya'}
print(dict1.key())

AttributeError: 'dict' object has no attribute 'key'

In [ ]:
dict3={"Dept":"cse","details":{"year":"II","sec":"D","count":71}}
print("year is",dict3["details"]["year"])
print("section is",dict3["details"]["sec"])
print("strength is",dict3["details"]["count"])


year is II
section is D
strength is 71


In [ ]:
idl=[34,56,78,39,100]
names=["joe","suji","siri","sofi"]


new_zip=(zip(idl,names))
for i in new_zip:
  print(i)

(34, 'joe')
(56, 'suji')
(78, 'siri')
(39, 'sofi')


In [ ]:
idl=[34,56,78,39,100]
names=["joe","suji","siri","sofi"]
new_dict=dict(zip(idl,names))
print(new_dict)

{34: 'joe', 56: 'suji', 78: 'siri', 39: 'sofi'}


In [ ]:
numpy

In [ ]:
import numpy as np
A=np.array([1,2,3,4])#id array
print(A.ndim)
print(A.shape)


1
(4,)


In [ ]:
#2 dim array
import numpy as np
#elements in each row =coloum
a=np.array([[1,2],[3,4]])
print(a.ndim)
print(a.shape)
print(a)



2
(2, 2)
[[1 2]
 [3 4]]


In [ ]:
#3 dim array
import numpy as np
a=np.array([[[3],[4],[5]],[[5],[6],[7]]])
print(a.ndim)
print(a.shape)
print(a)


3
(2, 3, 1)
[[[3]
  [4]
  [5]]

 [[5]
  [6]
  [7]]]


In [ ]:
A=np.ones((6,7))
print(A)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
A=np.zeros((6,7))
print(A)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
A=np.zeros((3,6,7))
print(A)


[[[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]


In [ ]:
A=np.eye(5)
print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
A=np.arange(1,10,2) #start,stop,step
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers that are divisible by 8 using a range function between 1 and 1000
A=np.arange(8,1001,8)
print(A)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
A=np.linspace(2,4,15)
print(A)

[2.         2.14285714 2.28571429 2.42857143 2.57142857 2.71428571
 2.85714286 3.         3.14285714 3.28571429 3.42857143 3.57142857
 3.71428571 3.85714286 4.        ]


In [ ]:
# spliting a range in to n numbers with having common differences
A=np.linspace(12,4)
print(A)
print(type(A))

[12.         11.83673469 11.67346939 11.51020408 11.34693878 11.18367347
 11.02040816 10.85714286 10.69387755 10.53061224 10.36734694 10.20408163
 10.04081633  9.87755102  9.71428571  9.55102041  9.3877551   9.2244898
  9.06122449  8.89795918  8.73469388  8.57142857  8.40816327  8.24489796
  8.08163265  7.91836735  7.75510204  7.59183673  7.42857143  7.26530612
  7.10204082  6.93877551  6.7755102   6.6122449   6.44897959  6.28571429
  6.12244898  5.95918367  5.79591837  5.63265306  5.46938776  5.30612245
  5.14285714  4.97959184  4.81632653  4.65306122  4.48979592  4.32653061
  4.16326531  4.        ]
<class 'numpy.ndarray'>


In [ ]:
#tuple, sets
#documentation
#qr code


In [ ]:
#mytuple
mytuple = ("apple", "banana", "cherry")
print(mytuple)

('apple', 'banana', 'cherry')


In [ ]:
#thistuple
thistuple = ("apple", "banana", "cherry")
print(thistuple)

('apple', 'banana', 'cherry')


In [ ]:
#duplicate
thistuple = ("apple", "banana", "cherry", "apple", "cherry")
print(thistuple)

('apple', 'banana', 'cherry', 'apple', 'cherry')


In [ ]:
#to generate how many items a tuple has use the len fuction
#len()
thistuple = ("apple", "banana", "cherry",6,7)
print(len(thistuple))

5


In [ ]:
#tuple
thistuple = ("apple",)
print(type(thistuple))

<class 'tuple'>


In [ ]:
#not a tuple
thistuple = ("apple")
print(type(thistuple))


<class 'str'>


In [ ]:
#string,int,boolean datatypes
tuple1 = ("apple", "banana", "cherry")
tuple2 = (1, 5, 7, 9, 3)
tuple3 = (True, False,False)
print(tuple1)
print(tuple2)
print(tuple3)

('apple', 'banana', 'cherry')
(1, 5, 7, 9, 3)
(True, False, False)


In [ ]:
#datatypes
tuple1 = ("abc", 34, True, 40, "male")
print(tuple1)

('abc', 34, True, 40, 'male')


In [ ]:
#constructor
thistuple = tuple(("apple", "banana", "cherry","kiwi","orange","dragen fruit"))
print(thistuple)


('apple', 'banana', 'cherry', 'kiwi', 'orange', 'dragen fruit')


In [1]:
#sorts
a=[6,8,9,5,12]
a.sort()
print(a)

[5, 6, 8, 9, 12]


In [2]:
a=[6,8,9,5,12]
b=sorted(a)
print(b)

[5, 6, 8, 9, 12]


In [3]:
a=(12,34,56,77)
b=sorted(a)
print(a)
print(b)

(12, 34, 56, 77)
[12, 34, 56, 77]


In [4]:
#sets
thisset = {"apple", "banana", "cherry"}
print(thisset)


{'apple', 'cherry', 'banana'}


In [5]:
#duplicate not allowed
thisset = {"apple", "banana", "cherry", "apple"}
print(thisset)


{'apple', 'cherry', 'banana'}


In [6]:
#datatypes
thisset = {"apple", "banana", "cherry", True, 1, 2}
print(thisset)


{True, 2, 'apple', 'cherry', 'banana'}


In [7]:
#false
thisset = {"apple", "banana", "cherry", False, True, 0}
print(thisset)


{False, True, 'apple', 'cherry', 'banana'}


In [8]:
#length of a set
thisset = {"apple", "banana", "cherry"}
print(len(thisset))


3


In [10]:
#string in datatypes
set1 = {"apple", "banana", "cherry"}
set2 = {1, 5, 7, 9, 3}
set3 = {True, False, False}
print(set1)
print(set2)
print(set3)


{'apple', 'cherry', 'banana'}
{1, 3, 5, 7, 9}
{False, True}


In [11]:
#type()
myset = {"apple", "banana", "cherry"}
print(type(myset))


<class 'set'>


In [12]:
#set()
thisset = set(("apple", "banana", "cherry")) # note the double round-brackets
print(thisset)


{'apple', 'cherry', 'banana'}
