In [ ]:
import numpy as np

In [ ]:
A = np.arange(1,13)
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
A = np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
A=np.linspace(2,8,10).reshape(5,2)
print(A)

[[2.         2.66666667]
 [3.33333333 4.        ]
 [4.66666667 5.33333333]
 [6.         6.66666667]
 [7.33333333 8.        ]]


In [ ]:
B=np.array([45,67,89,12,34,51,90,98]).reshape(2,2,2)
print(B)

[[[45 67]
  [89 12]]

 [[34 51]
  [90 98]]]


In [ ]:
B=np.array([45,67,89,12,34,51,90,98])
B.resize(2,2,2)#changes the shape of original array
#reshape - changes needs saving in another variable
print(B)

[[[45 67]
  [89 12]]

 [[34 51]
  [90 98]]]


In [ ]:
A=np.array([34,56,78,90])
B=np.array([7,9,3,12]) #list will throw an error while array iterate themselves
C=A-B
print(A-B)

[27 47 75 78]


In [ ]:
A=np.array([34,56,78,90])
B=np.array([7,9,3,12])
C=A-B
print(C)

[27 47 75 78]


In [ ]:
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("-----------------------")
print(B)
C=A*B # one on one multiplication
print("-----------------------")
print(C)


[[34 56]
 [78 90]]
-----------------------
[[ 7  9]
 [ 3 12]]
-----------------------
[[ 238  504]
 [ 234 1080]]


In [ ]:
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("-----------------------")
print(B)
C=A@B #matrix multiplication
print("-----------------------")
print(C)


[[34 56]
 [78 90]]
-----------------------
[[ 7  9]
 [ 3 12]]
-----------------------
[[ 406  978]
 [ 816 1782]]


In [ ]:
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("##########################")
print(B)
C=A.dot(B) # one on one multiplication
print("##########################")
print(C)


[[34 56]
 [78 90]]
##########################
[[ 7  9]
 [ 3 12]]
##########################
[[ 406  978]
 [ 816 1782]]


In [ ]:
A=np.array([34,56,78,90])
print(A.max()) #max and min only accepts numeric datatypes int and float
print(A.max())


90
90


In [ ]:
A=np.array([34,56,78.8,90.0])
print(A.max()) #max and min only accepts numeric datatypes int and float
print(A.max())


90.0
90.0


In [ ]:
A=np.array([34,56,78,90]).reshape(2,2)
print(A)
print("##########################")
print(A.max(axis=0))#axis -0=colum
print("--------------")
print(A.max(axis=1))#axis -1=row


[[34 56]
 [78 90]]
##########################
[78 90]
--------------
[56 90]


In [ ]:
A=np.array([34,56,78,90]).reshape(2,2)
print(A)
print("##########################")
print(A.min(axis=0))#axis -0=colum
print("--------------")
print(A.min(axis=1))#axis -1=row


[[34 56]
 [78 90]]
##########################
[34 56]
--------------
[34 78]


In [ ]:
#joing array
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("##########################")
print(B)
print("after vertically stacking the array")
print(np.hstack((A,B)))

[[34 56]
 [78 90]]
##########################
[[ 7  9]
 [ 3 12]]
after vertically stacking the array
[[34 56  7  9]
 [78 90  3 12]]


In [ ]:
#joing array
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("##########################")
print(B)
print("after vertically stacking the array")
print(np.vstack((A,B)))

[[34 56]
 [78 90]]
##########################
[[ 7  9]
 [ 3 12]]
after vertically stacking the array
[[34 56]
 [78 90]
 [ 7  9]
 [ 3 12]]


In [ ]:
A = np.arange(1,13).reshape(3,4)
print(A)
print("after dstack")
print(np.dstack(A))# no. of rows --->no. of groups
#no of colums in entry group --->no.of rows in every group


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
after dstack
[[[ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]
  [ 4  8 12]]]


In [ ]:
#spliting array
A = np.arange(18).reshape(6,3)
print(A)
print("After spliting")
np.vsplit(A,(3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After spliting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:

#spliting array
A = np.arange(18).reshape(6,3)
print(A)
print("After spliting")
np.vsplit(A,(2,5))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After spliting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([[15, 16, 17]])]

In [ ]:
#spliting array
A = np.arange(18).reshape(6,3)
print(A)
print("After spliting")
np.vsplit(A,(2,3))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After spliting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#spliting array
A = np.arange(18).reshape(6,3)
print(A)
print("After spliting")
np.hsplit(A,(6,6))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After spliting


[array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(6, 0), dtype=int64),
 array([], shape=(6, 0), dtype=int64)]

In [ ]:
#spliting array
A = np.arange(18).reshape(6,3)
print(A)
print("After spliting")
np.hsplit(A,(3,6))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After spliting


[array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(6, 0), dtype=int64),
 array([], shape=(6, 0), dtype=int64)]

In [ ]:
#spliting array
A = np.arange(18).reshape(6,3)
print(A)
print("After spliting")
np.hsplit(A,3)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After spliting


[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]])]

In [ ]:
#spliting array
A = np.arange(31,49).reshape(6,3)
print(A)
print(A.argmax())


[[31 32 33]
 [34 35 36]
 [37 38 39]
 [40 41 42]
 [43 44 45]
 [46 47 48]]
17


In [ ]:
A = np.linspace(17,12,18).reshape(6,3)
print(A)
print(A.argmax())


[[17.         16.70588235 16.41176471]
 [16.11764706 15.82352941 15.52941176]
 [15.23529412 14.94117647 14.64705882]
 [14.35294118 14.05882353 13.76470588]
 [13.47058824 13.17647059 12.88235294]
 [12.58823529 12.29411765 12.        ]]
0


In [ ]:
A=np.array([17,4,18,56,12,33,89,21,34,55,11,13]).reshape(3,4)
print(A)
print(A.argmax(axis = 0)) #position[0 0 0
                                     1 1 1 1]

[[17  4 18 56]
 [12 33 89 21]
 [34 55 11 13]]
[2 2 1 0]


In [ ]:
A=np.array([17,4,18,56,12,33,89,21,34,55,11,13]).reshape(3,4)
print(A)
print(A.argmin(axis = 0))

[[17  4 18 56]
 [12 33 89 21]
 [34 55 11 13]]
[1 0 2 2]


In [ ]:
A=np.array([17,4,18,56,12,33,89,21,34,55,11,13]).reshape(3,4)
print(A)
print(A.argmin(axis = 1))

[[17  4 18 56]
 [12 33 89 21]
 [34 55 11 13]]
[1 0 2]


In [ ]:
A=np.array([17,4,18,56,12,33,89,21,34,55,11,13]).reshape(3,4)
print(A)
print(A.argmax(axis = 1)) #position[0 1 2 3
                                     0 1 2 3]

[[17  4 18 56]
 [12 33 89 21]
 [34 55 11 13]]
[3 2 1]


In [ ]:
#statistics
#mean,median,std,var
A=np.array([12,34,25,66,71,88])
print("mean: ",np.mean(A))
print("median: ",np.median(A))
print("variance: ",np.var(A))
print("standard dev: ",np.std(A))



mean:  49.333333333333336
median:  50.0
variance:  743.888888888889
standard dev:  27.274326552435515


In [ ]:
#mean ,median,std,var formulas and fuctions in documentations in statistics

In [ ]:
A=np.pi
print(A)#radious


3.141592653589793


In [ ]:
np.rad2deg(A)

180.0

In [ ]:
A= np.array([np.pi/4, np.pi/3, np.pi/2, np.pi])
print(A)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
np.rad2deg(A)

array([ 45.,  60.,  90., 180.])

In [ ]:
C=np.array([0,45,60,90,120,180])
D=np.deg2rad(C)
print(D)

[0.52359878 0.78539816 1.04719755 1.57079633 2.0943951  3.14159265]


In [ ]:
np.sin(C)

array([-0.98803162,  0.85090352, -0.30481062,  0.89399666,  0.58061118,
       -0.80115264])

In [ ]:
np.cos(C)

array([ 0.15425145,  0.52532199, -0.95241298, -0.44807362,  0.81418097,
       -0.59846007])

In [ ]:
np.tan(C)

array([-6.4053312 ,  1.61977519,  0.32004039, -1.99520041,  0.71312301,
        1.33869021])

In [ ]:
np.arccos(C) #cos^-1

<ipython-input-94-a16d65da514c>:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(C)


array([nan, nan, nan, nan, nan, nan])

In [ ]:
np.arcsin(1) #sin^-1

1.5707963267948966

In [ ]:
np.arctan(1) #tan^-1

0.7853981633974483

In [ ]:
a=56
b=78
print(np.hypot(a,b)) #hypotneuse

96.02083107326243


In [ ]:
A=np.array([90,3,45,21,34,90,21])
print(np.where(A%2==0)) #even

(array([0, 4, 5]),)


In [ ]:
A=np.array([90,3,45,21,34,90,21])
print(np.where(A>25))

(array([0, 2, 4, 5]),)


search sort

In [1]:
import numpy as np

In [3]:
#search sort
#create an array in the elements
A=np.array([90,3,45,21,34,90,21])
print(np.searchsorted(A,90)) #output index of a sorted element!
#3,21,21,34,45,90,90


5


# linear algebra and ufunc






In [8]:
A=np.array([6,24,60,12,18])
B=np.array([6,4,10,5,4])
print(np.add(A,B))
print(np.subtract(A,B))
print(np.divide(A,B)) #quotient
print(np.mod(A,B))#rem
print(np.divmod(A,B))#qand r
#(array([1,,6,6,2,4]),array([0,0,0,2,2]))



[12 28 70 17 22]
[ 0 20 50  7 14]
[1.  6.  6.  2.4 4.5]
[0 0 0 2 2]
(array([1, 6, 6, 2, 4]), array([0, 0, 0, 2, 2]))


In [9]:
A=np.array([6,12,34,56,10])
print(np.diff(A))

[  6  22  22 -46]


# sort

In [11]:
A=np.array([6,12,34,56,10])
B=np.array([6,4,10,5,4])
print(np.union1d(A,B))

[ 4  5  6 10 12 34 56]


In [13]:
A=np.array([6,12,34,56,10])
B=np.array([6,4,10,5,4])
print(np.setdiff1d(A,B))

[12 34 56]


In [15]:
A=np.array([6,12,34,56,10])
B=np.array([6,4,10,5,4])
print(np.intersect1d(A,B))

[ 6 10]


# rounding

In [16]:
A=np.around(3.4567,9)
print(A)

3.4567


In [17]:
a=np.trunc([-4.678,9.5678])
print(a)

[-4.  9.]


In [18]:
a=np.fix([-3.56674,9.54])
print(a)

[-3.  9.]


In [19]:
a=np.floor([-3.455,2.456])
print(a)

[-4.  2.]


In [20]:
a=np.ceil([-3.21457,4.5678])
print(a)

[-3.  5.]


In [22]:
a=np.array([4.1,-4.1])
print(np.trunc(a))

[ 4. -4.]


# more functions

In [23]:
A=np.array([3,4,16,19,10])
print(np.cumsum(A))

[ 3  7 23 42 52]


In [24]:
A=np.array([3,4,16,19,10])
print(np.cumprod(A))

[    3    12   192  3648 36480]


In [25]:
print(np.lcm(46,56))
print(np.gcd(445,665))

1288
5


In [26]:
Ar=np.array([45,65,30])
print(np.lcm.reduce(Ar))

1170


In [27]:
Ar=np.array([45,65,30])
print(np.gcd.reduce(Ar))

5


In [31]:
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


# random

In [36]:
from numpy import random as rd

In [37]:
A = rd.rand() #n #default limit 0 to 0.99
print(A)

0.7149038819748442


In [38]:
A = rd.rand(10) #ran n numbers
print(A)

[0.61950986 0.79484425 0.89102232 0.75100552 0.7536769  0.60302046
 0.51903633 0.1429843  0.13059782 0.6122682 ]


In [42]:
A = rd.rand(4)#rand 0,1,2,3
print(A)

[0.55036663 0.50924245 0.26244691 0.78384788]


In [41]:
A = rd.randint(4)#randint(limit)==># #limit 0,1,2,3
print(A)

3


In [43]:
A=rd.randint(50,size=(2,3))#limit
print(A)

[[ 2 25 23]
 [45 39 36]]


In [45]:
A=rd.randint(4,size=6)#limit
print(A)

[3 1 0 3 3 2]


# joins

In [46]:
A=np.array ([1,2,3])
B=np.array([4,5,6])
#1x4+ 2x5 + 3x6
print(np.inner(A,B))

32


In [47]:
A=np.array ([1,2,3])
B=np.array([4,5,6])
#1x(4,5,6) 2x(4,5,6)3x(4,5,6)
print(np.outer(A,B))


[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [48]:
A=np.array ([1,2,3])
B=np.array([4,5,6])
print(np.cross(A,B))


[-3  6 -3]
